# Generated by Django 4.2 on 2024-08-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="напишите название",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="напишите название",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="напишите название",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("XS", "Xs"), ("S", "S")],
                        help_text="выберите размер",
                        max_length=2,
                        verbose_name="размер",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="выберите категорию",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        related_query_name="items",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        help_text="выберите цвет",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        related_query_name="items",
                        to="catalog.color",
                        verbose_name="цвет",
                    ),
                ),
            ],
            options={
                "verbose_name": "абстрактная модель",
                "verbose_name_plural": "абстрактные модели",
                "abstract": False,
            },
        ),
    ]
