# Generated by Django 4.2 on 2024-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                choices=[("XS", "XS"), ("S", "S")],
                help_text="выберите размер",
                max_length=2,
                verbose_name="размер",
            ),
        ),
    ]
