# Generated by Django 4.2 on 2024-08-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_item_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="color",
            options={"verbose_name": "цвет", "verbose_name_plural": "цвета"},
        ),
    ]
