# Generated by Django 4.2 on 2024-08-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_tshirt_delete_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tshirt",
            name="name",
        ),
    ]
