# Generated by Django 4.2 on 2024-08-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_tshirt_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tshirt",
            unique_together={("category", "color", "size")},
        ),
    ]
