# Generated by Django 4.2 on 2024-08-03 16:05

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_tshirtmainimage_embroiderymainimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embroiderymainimage",
            name="embroidery",
            field=models.OneToOneField(
                help_text="изображение вышивки на футболке",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                related_query_name="main_image",
                to="catalog.embroidery",
                verbose_name="футболка",
            ),
        ),
        migrations.CreateModel(
            name="EmbroiderySecondaryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="загрузите изображение",
                        upload_to=catalog.models.get_path_image,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "embroidery",
                    models.OneToOneField(
                        help_text="изображение вишивки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_image",
                        related_query_name="secondary_image",
                        to="catalog.embroidery",
                        verbose_name="футболка",
                    ),
                ),
            ],
            options={
                "verbose_name": "вторичное изображение",
                "verbose_name_plural": "вторичные изображения",
            },
        ),
    ]
