version: '3'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    command: npm start
    expose:
      - "3000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
