# Generated by Django 4.2.16 on 2024-12-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0025_alter_cart_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        help_text="идентификатор платежа в платежной системе",
                        max_length=255,
                        null=True,
                        verbose_name="идентификатор платежа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PD", "В ожидании"),
                            ("WC", "Ожидает подтверждения"),
                            ("SD", "Успешно"),
                            ("CN", "Отменён"),
                            ("FL", "Ошибка"),
                        ],
                        default="PD",
                        help_text="статус платежа",
                        max_length=2,
                        verbose_name="статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="дата создания платежа",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="заказ для оплаты",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        related_query_name="payment",
                        to="catalog.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "платёж",
                "verbose_name_plural": "платежи",
                "ordering": ["-created_at"],
            },
        ),
    ]
