# Generated by Django 4.2.16 on 2024-12-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="confirmation_url",
            field=models.URLField(
                default=1,
                help_text="url для подтверждения платежа",
                verbose_name="url для подтверждения платежа",
            ),
            preserve_default=False,
        ),
    ]
