# Generated by Django 4.2.16 on 2024-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_confirmation_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PD", "В ожидании"),
                    ("SD", "Успешно"),
                    ("CN", "Отменён"),
                    ("FL", "Ошибка"),
                ],
                default="PD",
                help_text="статус платежа",
                max_length=2,
                verbose_name="статус",
            ),
        ),
    ]
