# Generated by Django 4.2.16 on 2024-12-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("succeeded", "Успешно"),
                    ("canceled", "Отменён"),
                ],
                default="pending",
                help_text="статус платежа",
                max_length=9,
                verbose_name="статус",
            ),
        ),
    ]
