# Generated by Django 4.2.16 on 2025-05-17 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "promo_code",
                    models.CharField(
                        help_text="Промокод для скидки",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Промокод",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        help_text="Размер скидки по промокоду (в процентах или рублях)",
                        verbose_name="Скидка",
                    ),
                ),
            ],
            options={
                "verbose_name": "промокод",
                "verbose_name_plural": "промокоды",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Текст вопроса", verbose_name="Вопрос"
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        help_text="Правильный ответ на вопрос",
                        verbose_name="Правильный ответ",
                    ),
                ),
                (
                    "wrong_answer1",
                    models.TextField(
                        help_text="Первый неправильный ответ",
                        verbose_name="Неправильный ответ 1",
                    ),
                ),
                (
                    "wrong_answer2",
                    models.TextField(
                        help_text="Второй неправильный ответ",
                        verbose_name="Неправильный ответ 2",
                    ),
                ),
                (
                    "wrong_answer3",
                    models.TextField(
                        help_text="Третий неправильный ответ",
                        verbose_name="Неправильный ответ 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.CreateModel(
            name="WrongAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Вопрос, на который был дан неправильный ответ",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "user_answer",
                    models.TextField(
                        help_text="Ответ, который дал пользователь",
                        verbose_name="Ответ пользователя",
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        help_text="Правильный ответ на вопрос",
                        verbose_name="Правильный ответ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, который дал неправильный ответ",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "неправильный ответ",
                "verbose_name_plural": "неправильные ответы",
                "unique_together": {("user", "question")},
            },
        ),
    ]
