# Generated by Django 4.2 on 2024-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_verified_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified_email",
            field=models.BooleanField(
                default=False,
                verbose_name="подтвержденный адрес электронной почты",
            ),
        ),
    ]
