# Generated by Django 4.2.16 on 2024-12-08 11:36

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[users.validators.PasswordValidator],
                verbose_name="password",
            ),
        ),
    ]
