# Generated by Django 4.2.16 on 2025-05-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_userrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bonus",
            field=models.IntegerField(default=0),
        ),
    ]
