# Generated by Django 4.2.16 on 2025-05-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_bonus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bonus",
            field=models.PositiveIntegerField(
                default=0,
                help_text="бонусы пользователя",
                verbose_name="бонус",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="users",
                to="users.userrole",
                verbose_name="роли",
            ),
        ),
    ]
