# Generated by Django 4.2.16 on 2025-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_bonus_alter_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.userrole",
                verbose_name="роли",
            ),
        ),
    ]
