name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install Python dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements/prod.txt

    - name: Run Django tests
      run: |
        cd backend
        python manage.py test

    - name: Set up Node.js
      uses: actions/setup-node@v20.17.0
      with:
        node-version: '20.17.0'

    - name: Install Node.js dependencies
      run: |
        cd frontend
        yarn install

    - name: Run React tests
      run: |
        cd frontend
        yarn test