name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: myprojectuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myproject
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
        ports:
          - 9200:9200
        options: >-
          --health-cmd="curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          xpack.security.enabled: "false"
      

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install Python dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
    
    - name: linting
      run: |
        cd backend
        flake8 --verbose .
        black --check --verbose -- .

    - name: Run Django tests
      env:
        SECRET_KEY: Test
        YOOKASSA_SHOP_ID: ${{ secrets.YOOKASSA_SHOP_ID }}
        YOOKASSA_SECRET_KEY: ${{ secrets.YOOKASSA_SECRET_KEY }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        DEBUG: True
        SITE_URL: https://test.com
      run: |
        cd backend
        python manage.py test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'

    - name: Install Node.js dependencies
      run: |
        cd frontend
        yarn install